name: pangram
version: 2.0.0.12

dependencies:
  - base
  - mtl
  - containers
  - extra

library:
  exposed-modules: Pangram
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl
    - containers
    - extra

executables:
  pangram:
    main:                Pangram.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Pangram
    dependencies:
    - pangram

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
